services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-bot
    restart: unless-stopped
    ports:
      - "8886:8080"
    env_file:
      - ../.env
    volumes:
      - ../data:/app/app_database
      - ../logs:/app/logs